---
- name: Install Certbot
  package: "name={{ certbot_package }} state=present"
  delegate_to: localhost

- name: Set Certbot script variable
  set_fact:
    certbot_script: "{{ certbot_package }}"
  delegate_to: localhost
