---
- name: Installation Apache
  become: yes
  with_items: "{{ debian_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: Start Apache
  become: yes
  service:
    name: apache2
    state: started
